### ISSUE TITLE
Templates and Pages do not compile correctly

### ISSUE THREAD

**Issue by jimmytsao** [onenorth/kickstart#1] opened 2015-04-16 15:25 UTC
Templates and Pages that get compiled into their own html files do not show the actual content in the compiled html.

**Comment by askesian** [comment] 2015-04-16 15:45
Thanks for reporting the issue. I am currently not able to reproduce locally - will do some more thorough testing today.

**Comment by askesian** [comment] 2016-01-29 04:48
This was resolved in-person.

**Closed** 2016-01-29 04:47 UTC
Labels: bug
